# **Homework**: Data talks club data engineering zoomcamp Data loading workshop

Hello folks, let's practice what we learned - Loading data with the best practices of data engineering.

Here are the exercises we will do

# 1. Use a generator

Remember the concept of generator? Let's practice using them to futher our understanding of how they work.

Let's define a generator and then run it as practice.

**Answer the following questions:**

- **Question 1: What is the sum of the outputs of the generator for limit = 5?**
- **Question 2: What is the 13th number yielded**

I suggest practicing these questions without GPT as the purpose is to further your learning.

In [ ]:
def square_root_generator(limit):
    n = 1
    while n <= limit:
        yield n ** 0.5
        n += 1

# Example usage:
limit = 5
generator = square_root_generator(limit)

for sqrt_value in generator:
    print(sqrt_value)

1.0
1.4142135623730951
1.7320508075688772
2.0
2.23606797749979

# 2. Append a generator to a table with existing data


Below you have 2 generators. You will be tasked to load them to duckdb and answer some questions from the data

1. Load the first generator and calculate the sum of ages of all people. Make sure to only load it once.
2. Append the second generator to the same table as the first.
3. **After correctly appending the data, calculate the sum of all ages of people.**

In [ ]:
def people_1():
    for i in range(1, 6):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 25 + i, "City": "City_A"}

for person in people_1():
    print(person)


def people_2():
    for i in range(3, 9):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 30 + i, "City": "City_B", "Occupation": f"Job_{i}"}


for person in people_2():
    print(person)

{'ID': 1, 'Name': 'Person_1', 'Age': 26, 'City': 'City_A'}
{'ID': 2, 'Name': 'Person_2', 'Age': 27, 'City': 'City_A'}
{'ID': 3, 'Name': 'Person_3', 'Age': 28, 'City': 'City_A'}
{'ID': 4, 'Name': 'Person_4', 'Age': 29, 'City': 'City_A'}
{'ID': 5, 'Name': 'Person_5', 'Age': 30, 'City': 'City_A'}
{'ID': 3, 'Name': 'Person_3', 'Age': 33, 'City': 'City_B', 'Occupation': 'Job_3'}
{'ID': 4, 'Name': 'Person_4', 'Age': 34, 'City': 'City_B', 'Occupation': 'Job_4'}
{'ID': 5, 'Name': 'Person_5', 'Age': 35, 'City': 'City_B', 'Occupation': 'Job_5'}
{'ID': 6, 'Name': 'Person_6', 'Age': 36, 'City': 'City_B', 'Occupation': 'Job_6'}
{'ID': 7, 'Name': 'Person_7', 'Age': 37, 'City': 'City_B', 'Occupation': 'Job_7'}
{'ID': 8, 'Name': 'Person_8', 'Age': 38, 'City': 'City_B', 'Occupation': 'Job_8'}

# 3. Merge a generator

Re-use the generators from Exercise 2.

A table's primary key needs to be created from the start, so load your data to a new table with primary key ID.

Load your first generator first, and then load the second one with merge. Since they have overlapping IDs, some of the records from the first load should be replaced by the ones from the second load.

After loading, you should have a total of 8 records, and ID 3 should have age 33.

Question: **Calculate the sum of ages of all the people loaded as described above.**

# Solution: First make sure that the following modules are installed:

# Solution for question 1

In [ ]:
def square_root_generator(limit):
    n = 1
    while n <= limit:
        yield n ** 0.5
        n += 1

# Example usage:
limit = 5
generator = square_root_generator(limit)

sum = 0
for sqrt_value in generator:
    sum += sqrt_value

print(f'Answer {sum}')

Answer 8.382332347441762

# Solution for question 2

In [ ]:
def square_root_generator(limit):
    n = 1
    while n <= limit:
        yield n ** 0.5
        n += 1

# Example usage:
limit = 13
generator = square_root_generator(limit)

count = 1
for sqrt_value in generator:
    print(f"Count {count} value: {sqrt_value}")
    count += 1

Count 1 value: 1.0
Count 2 value: 1.4142135623730951
Count 3 value: 1.7320508075688772
Count 4 value: 2.0
Count 5 value: 2.23606797749979
Count 6 value: 2.449489742783178
Count 7 value: 2.6457513110645907
Count 8 value: 2.8284271247461903
Count 9 value: 3.0
Count 10 value: 3.1622776601683795
Count 11 value: 3.3166247903554
Count 12 value: 3.4641016151377544
Count 13 value: 3.605551275463989

# Solution for question 3

In [ ]:
#Install the dependencies
%%capture
!pip install dlt[duckdb]

In [ ]:
# to do: homework :)
import dlt

pipeline = dlt.pipeline(destination='duckdb',
                        dataset_name='homework'
                        )

info = pipeline.run(people_1(), table_name='peoples', write_disposition='replace')

print(info)

Pipeline dlt_colab_kernel_launcher load step completed in 0.19 seconds
1 load package(s) were loaded to destination duckdb and into dataset homework
The duckdb destination used duckdb:////content/dlt_colab_kernel_launcher.duckdb location to store data
Load package 1708005909.740995 is LOADED and contains no failed jobs

In [ ]:
import duckdb

conn = duckdb.connect(f"{pipeline.pipeline_name}.duckdb")

conn.sql(f"SET search_path = '{pipeline.dataset_name}'")

In [ ]:
print("Tables: ")
display(conn.sql("show tables"))

Tables:

┌─────────────────────┐
│        name         │
│       varchar       │
├─────────────────────┤
│ _dlt_loads          │
│ _dlt_pipeline_state │
│ _dlt_version        │
│ peoples             │
└─────────────────────┘

In [ ]:
display(conn.sql("SELECT SUM(age) FROM peoples"))

┌──────────┐
│ sum(age) │
│  int128  │
├──────────┤
│      140 │
└──────────┘

In [ ]:
info = pipeline.run(people_2(),
                    table_name='peoples',
                    write_disposition='append')
print(info)

Pipeline dlt_colab_kernel_launcher load step completed in 0.52 seconds
1 load package(s) were loaded to destination duckdb and into dataset homework
The duckdb destination used duckdb:////content/dlt_colab_kernel_launcher.duckdb location to store data
Load package 1708006320.1449454 is LOADED and contains no failed jobs

In [ ]:
display(conn.sql("SELECT * FROM peoples").df())

    id      name  age    city        _dlt_load_id         _dlt_id occupation
0    1  Person_1   26  City_A   1708005909.740995  1n1UAHUW5bGKew       None
1    2  Person_2   27  City_A   1708005909.740995  eH9MhFkZBn15Eg       None
2    3  Person_3   28  City_A   1708005909.740995  5Su+DswQJvB9Ig       None
3    4  Person_4   29  City_A   1708005909.740995  0n56vLY0oFOGZg       None
4    5  Person_5   30  City_A   1708005909.740995  EA7g9ZA9uAWuTQ       None
5    3  Person_3   33  City_B  1708006320.1449454  6VMIgSQNMX5/1g      Job_3
6    4  Person_4   34  City_B  1708006320.1449454  zq4Pe04xKmHaWw      Job_4
7    5  Person_5   35  City_B  1708006320.1449454  3tosqGRGA1m8+g      Job_5
8    6  Person_6   36  City_B  1708006320.1449454  I3d5s1CWF7W0HA      Job_6
9    7  Person_7   37  City_B  1708006320.1449454  Qh/6b7tX5RXSCw      Job_7
10   8  Person_8   38  City_B  1708006320.1449454  8vVA17YCGshOog      Job_8

In [ ]:
display(conn.sql("SELECT SUM(age) FROM peoples"))

┌──────────┐
│ sum(age) │
│  int128  │
├──────────┤
│      353 │
└──────────┘

# Solution for question 4

In [ ]:
pipeline = dlt.pipeline(destination='duckdb', dataset_name='unique')


info = pipeline.run(people_1(),
                table_name='unique_peoples',
                primary_key="id",
                write_disposition='replace')
print(info)

2024-02-15 14:34:52,084|[WARNING              ]|181|138831823003648|dlt|logger.py|wrapper:30|The pipeline `run` method will now load the pending load packages. The data you passed to the run function will not be loaded. In order to do that you must run the pipeline again

Pipeline dlt_colab_kernel_launcher load step completed in 0.27 seconds
1 load package(s) were loaded to destination duckdb and into dataset unique
The duckdb destination used duckdb:////content/dlt_colab_kernel_launcher.duckdb location to store data
Load package 1708007679.4367628 is LOADED and contains no failed jobs

In [ ]:
info = pipeline.run(people_2(),
                table_name='unique_peoples',
                primary_key="id",
                write_disposition='merge')
print(info)

Pipeline dlt_colab_kernel_launcher load step completed in 0.46 seconds
1 load package(s) were loaded to destination duckdb and into dataset unique
The duckdb destination used duckdb:////content/dlt_colab_kernel_launcher.duckdb location to store data
Load package 1708007710.625806 is LOADED and contains no failed jobs

In [ ]:
conn.sql(f"SET search_path = '{pipeline.dataset_name}'")

display(conn.sql("show tables"))

┌─────────────────────┐
│        name         │
│       varchar       │
├─────────────────────┤
│ _dlt_loads          │
│ _dlt_pipeline_state │
│ _dlt_version        │
│ unique_peoples      │
└─────────────────────┘

In [ ]:
display(conn.sql("SELECT SUM(age) FROM unique_peoples"))

┌──────────┐
│ sum(age) │
│  int128  │
├──────────┤
│      266 │
└──────────┘

In [ ]:
display(conn.sql("SELECT * FROM unique_peoples"))

┌───────┬──────────┬───────┬─────────┬────────────────────┬────────────────┬────────────┐
│  id   │   name   │  age  │  city   │    _dlt_load_id    │    _dlt_id     │ occupation │
│ int64 │ varchar  │ int64 │ varchar │      varchar       │    varchar     │  varchar   │
├───────┼──────────┼───────┼─────────┼────────────────────┼────────────────┼────────────┤
│     1 │ Person_1 │    26 │ City_A  │ 1708007679.4367628 │ fQkcd6F7NvF96g │ NULL       │
│     2 │ Person_2 │    27 │ City_A  │ 1708007679.4367628 │ THUaSAKQO4tfvQ │ NULL       │
│     5 │ Person_5 │    35 │ City_B  │ 1708007710.625806  │ xR9SOsGPRE5cSQ │ Job_5      │
│     7 │ Person_7 │    37 │ City_B  │ 1708007710.625806  │ Q8fbxrVsVgGrXw │ Job_7      │
│     4 │ Person_4 │    34 │ City_B  │ 1708007710.625806  │ xloenufPFUsNPA │ Job_4      │
│     8 │ Person_8 │    38 │ City_B  │ 1708007710.625806  │ /++3MddhHiQ0Fw │ Job_8      │
│     3 │ Person_3 │    33 │ City_B  │ 1708007710.625806  │ rfXdWc/ke0+10w │ Job_3      │
│     6 │ Person_6 │    36 │ City_B  │ 1708007710.625806  │ GH17XCOAsGNCLw │ Job_6      │
└───────┴──────────┴───────┴─────────┴────────────────────┴────────────────┴────────────┘

Questions? difficulties? We are here to help.
- DTC data engineering course channel: https://datatalks-club.slack.com/archives/C01FABYF2RG
- dlt's DTC cohort channel: https://dlthub-community.slack.com/archives/C06GAEX2VNX